### ISSUE TITLE
Sviluppo bundle Symfony per autenticazione SPID

### ISSUE THREAD

**Issue by alexrj** [italia/spid-symfony-bundle#1]
Ci sono due strade per implementare un bundle per Symfony:

1. usare un middleware come Shibboleth
2. implementare tutto direttamente nel plugin (self-contained)

Per i dettagli sulle due possibili soluzioni si vedano le considerazioni scritte nell'analoga [issue per SPID-Django](https://github.com/italia/spid-django/issues/1).

Lo scopo di un plugin SPID dovrebbe essere quello di:

* facilitare l'integrazione del [bottone di login](https://github.com/italia/spid-sp-access-button) nella posizione desiderata
* fornire metodi semplici per leggere le informazioni sullo stato di autenticazione dell'utente e i relativi attributi

Può essere invece preferibile integrare il bundle SPID con un bundle che fa la gestione degli utenti (ad es. FOSUserBundle)? Qual è la soluzione più portabile/compatibile e al tempo stesso più conveniente?

La soluzione 2 sopra indicata (implementazione self-contained senza dipendenza da Shibboleth) sembra la più conveniente, visto che per Symfony ci sono già almeno due bundle per SAML:

* https://github.com/pdias/SamlBundle
* https://github.com/lightSAML/SpBundle

Quale conviene usare? Dovremmo ovviamente usarli come dipendenza, non farne un fork.

**Comment by marcoalbarelli** [comment]
Salve
Come detto tempo fa con @umbros sto portando avanti lo sviluppo di una soluzione "shibboleth-free" per un cliente. La nostra casistica avrà bisogno di una soluzione slegata da shibboleth per poter scalare senza problemi.
Lato Symfony l'idea è di rimpiazzare l'adapter che usiamo attualmente in produzione (shibboleth based) con quello autonomo
L'adapter fornirà delle istanze di `Symfony\Component\Security\Core\User\UserInterface` e implementerà l'autenticazione tramite una estenzione di `Symfony\Component\Security\Guard\AbstractGuardAuthenticator`

L'idea di base è di usare il fork [italia/spid-sp-simplesamlphp](url) e usarlo  come dipendenza per la parte SAML

Il sistema che ho sviluppato per Opencontent è già attivo in produzione (https://stanzadelcittadino.it) e fornisce autenticazione rispetto alla CPS trentina, sto "ripulendo" quel codice per renderlo generico, creando un bundle riutilizzabile.

Ho già pronta una prima PR molto larvale, semplicemente non volevo farla verso  master (sono un convinto gitflow-ista)
Se non sento obiezioni procedo così:
Prendo in carico il task
Creo il ramo develop
apro una PR in WIP con la feature dello sviluppo di base

Compatibilmente con il tempo dovrei riuscire nella prossima settimana a chiuderla e dare una versione 0.01alfa che funzioni verso lo [italia/spid-testenv-identityserver.git](url)

**Comment by marcoalbarelli** [comment]
P.S.
Riguardo la questione FOSUserBundle

Il bundle che andremo a sviluppare fornirà delle UserInterface generiche, compatibili con quello che serve allo FosUserBundle.

Il FosUserBundle è la soluzione che abbiamo usato per la stanzadelcittadino.iit[](url) quindi l'idea è di fornire un how-to con dei default sensati per una integrazione semplice e meno dolorosa possibile, mostrando un mix di autenticazione shibboleth e  user:password in base alle rotte

Al momento usiamo tre schemi di autenticazione:
#shibboleth (lato cittadino)
#username:password (lato admin)
#token (lato API server2server)

**Comment by alexrj** [comment]
Questa è una delle challenge che proponiamo domani e dopodomani agli sviluppatori di [Hack.Developers](https://hack.developers.italia.it/).

Ti propongo di pubblicare il tuo codice, anche grezzo, in un tuo fork. Probabilmente qualcuno durante Hack.Developers potrà aiutarti a completarlo. Ti chiederei di non usare master, e anche per lo sviluppo ti consiglierei in ogni caso di usare un tuo fork e poi di usare una PR verso questo.

**Comment by marcoalbarelli** [comment]
Ok, mi ritiro in buon ordine :)
Apro una PR in WIP dal mio fork a questo master (e mi disassegno il task)
