### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by manzolo** [italia/spid-symfony-bundle#10]
- Using Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty() at path "spid.sp_attributeconsumingservice" has no effect, consider requiresAtLeastOneElement() instead. In 4.0 both methods will behave the same

- Using Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty() at path "spid.sp_assertionconsumerservice" has no effect, consider requiresAtLeastOneElement() instead. In 4.0 both methods will behave the same.

**Comment by marcoalbarelli** [comment]
Sounds reasonable if it has no drawbacks for the 3.x LTS

**Comment by manzolo** [comment]
I'm developing with symfony 3.4.* LTS

**Comment by marcoalbarelli** [comment]
What's the status on this? Do you have a PR ready?
