### ISSUE TITLE
spid-smart-button integration

### ISSUE THREAD

**Issue by simevo** [italia/spid-symfony-bundle#20]
see:
- simevo/spid-php-lib-example@48a80db
- https://github.com/simevo/spid-wordpress/issues/2

**Comment by marcoalbarelli** [comment]
I integrated the button in a different way.
Since the documentation of the button states that it should be retrieved from the official CDNs I added a quick dump of the current state of the [spid-smart-button](https://github.com/italia/spid-smart-button) as static files
