### ISSUE TITLE
Trying to get property 'attributes' of non-object -> SpidAuthenticator.php (line 55) 

### ISSUE THREAD

**Issue by manzolo** [italia/spid-symfony-bundle#26]
Credo sia cambiato il tipo di oggetto che restituisce le credentials (prima std-object, adesso array)

Ho provato a modificare 
namespace Italia\SpidSymfonyBundle\Security;
class SpidAuthenticator extends AbstractGuardAuthenticator
...

Da:

    public function getUser($credentials, UserProviderInterface $userProvider): UserInterface
    {
        return $userProvider->loadUserByUsername($credentials->attributes['fiscalNumber']);
    }

a:

    public function getUser($credentials, UserProviderInterface $userProvider): UserInterface
    {
        return $userProvider->loadUserByUsername($credentials["attributes"]['fiscalNumber']);
    }

E cosi torna a funzionare

**Comment by marcoalbarelli** [comment]
A me funziona in produzione. 
È cambiato qualcosa nella libreria spid-php-lib?
In ogni caso fammi una PR se hai un attimo, grazie :)

**Comment by manzolo** [comment]
La stavo preparando ;-)

**Comment by manzolo** [comment]
Me ne sono accorto qui:
https://travis-ci.org/manzolo/spid-symfony3-example/builds
fallivano i test sul progetto di example che avevamo buttato giù con Simevo, ma era rimasto fermo a una versione di italia/spid-symfony-bundle vecchiotta. In questo momento punta a : 
 "italia/spid-symfony-bundle": "v0.2.2-beta",
